#pragma config(Motor,  port6,           left_drive_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           right_drive_motor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	void drive()
	{
		if (vexRT[Ch2] > 15)
		{
			motor[left_drive_motor] = 127;
			motor[right_drive_motor] = 127;
		}
		if (vexRT[Ch2] < -15)
		{
			motor[left_drive_motor] = -127;
			motor[right_drive_motor] = -127;
		}
		if (vexRT[Ch1] > 15)
		{
			motor[left_drive_motor] = 127;
			motor[right_drive_motor] = -127;
		}
		if (vexRT[Ch1] < -15)
		{
			motor[left_drive_motor] = -127;
			motor[right_drive_motor] = 127;
		}
		if (vexRT[Ch1] < 15 && vexRT[Ch1] > -15)
		{
			motor[left_drive_motor] = 0;
			motor[right_drive_motor] = 0;
		}
		if (vexRT[Ch2] < 15 && vexRT[Ch2] > -15)
		{
			motor[left_drive_motor] = 0;
			motor[right_drive_motor] = 0;
		}
	}
}
